apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: project
  name: project-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-backend
  template:
    metadata:
      labels:
        app: project-backend
    spec:
      containers:
        - name: project-backend
          image: PROJECTBACK/IMAGE
          resources:
            limits:
              memory: '128Mi'
              cpu: '500m'
          envFrom:
              - configMapRef:
                  name: postgres-configuration
              - secretRef:
                  name: db-key