apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: project
  name: project-backend-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-backend
  template:
    metadata:
      labels:
        app: project-backend
    spec:
      containers:
        - name: project-backend
          image: PROJECT/IMAGE
          envFrom:
              - configMapRef:
                  name: postgres-configuration
              - secretRef:
                  name: db-key